export const ORGANIZATION_IDS = {
    PERSONAL_VINCULACIONES: 'fIVd5L9F3AfiC94NETPaQZvlwqOuZ183',
    PERSONAL_ESTABLECIMIENTOS_NAVALES: 'ibQ6dYjZhckwvZTA2ZqJpmdx1FhoUEgE',
    PERSONAL_CIVIL: 'iHXAGkJhxhZPgHbMnuXDD9iiZW4TDqDu'
  } as const;